######################################
## Site settings                    ##
######################################
title:       Hajar Zaid
email:       hzaid@gradcenter.cuny.edu
author:      Hajar Zaid
description: "Math and Data Science student"
baseurl:     ""
url:         "https://hajarzaid.github.io"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

######################################
## Optional features                ##
######################################
animated:             false
show_related_posts:   false
show_post_footers:    True
show_social_icons:    True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

######################################
## Optional site sections           ##
######################################
show_talks_section:     true
show_workshops_section: true

######################################
## Disqus post comments             ##
## (leave blank to disable Disqus)  ##
######################################
disqus_shortname: 'juniortheme-live'

##########################################################################
## Facebook Comments plugin                                             ##
## (leave blank to disable Facebook Comments, otherwise set it to true) ##
##########################################################################
facebook_comments:
facebook_appid:
facebook_comments_number: 10

###################################
## Social icons                  ##
###################################
github_username: thundergolfer
bitbucket_username:
stackoverflow_id:
twitter_username: jonobelotti_io
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: jonathonbelotti
angellist_username:
medium_id: thundergolfer
youtube_channel_id: UCSP7fMKwmaXaZhViAV2Vgvg
bitcoin_url:
paypal_url:
flattr_button:

###################################
## Post sharing icons            ##
###################################
show_sharing_icons: True
# Change to 'true' to enable individual icons
share_facebook: True
share_twitter: True
share_googleplus: True
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: True
share_stumbleupon: false
share_hackernews: True

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: Hello, my name is Hajar Zaid, and I’m a master's student in Data Science at the CUNY Graduate Center, taking courses in both the mathematics and computer science departments. My research interests span randomized numerical algorithms, random matrix theory, numerical optimization, and the theoretical foundations of deep learning. I am particularly fascinated by the behavior of deep learning models in high-dimensional spaces.

I am currently a research intern at the Icahn School of Medicine, working under the mentorship of Evan Schaffer, where I study random matrices in the context of neural representations. Additionally, I am collaborating with Tyler Chen’s group at NYU Courant Institute of Mathematical Sciences, focusing on iterative methods for solving linear systems. Next semester, I will begin a year-long capstone project on randomized numerical algorithms under the supervision of Victor Pan.

I am seeking industry-based research opportunities for the upcoming summer to gain hands-on experience with real-world applications. My goal is to focus my PhD on research that is not only valuable to academia but also has practical relevance to industry. By identifying real-world challenges, I aim to ensure my work contributes meaningfully to both fields.







  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

############################################
## Build settings                         ##
############################################
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink:    pretty
paginate:     4
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

#################################################
## Collections (for 'Design' section of site)  ##
#################################################
collections:
  portfolio:
    output: true
