title: Hajar Zaid
description: 
theme: just-the-docs

nav_order:
  - index.md      # This is the homepage
  - Research.md   # Link to Research page
  - Notes.md      # Link to Notes page
  - Teaching/     # Folder for Teaching section
  - CUNY DRP.md   # If this is a file you want to show
